In [4]:
import numpy as np


In [6]:
np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [7]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [8]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [9]:
print(type(data))

<class 'numpy.ndarray'>


In [10]:
print('first value in data:', data[0, 0])


first value in data: 0.0


In [11]:
print('middle value in data:', data[30, 20])

middle value in data: 13.0


In [12]:
print(data[0:4, 0:10])


[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [13]:
"oxygen"[1:4]

'xyg'

In [14]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [15]:
print('first value in data:', data[0, 0])


first value in data: 0.0


In [16]:
print(data.shape)


(60, 40)


In [17]:
print('last value in data:', data[59,39])


last value in data: 0.0


In [18]:
print('middle value in data:', data[30, 20])



middle value in data: 13.0


In [19]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [20]:
m = np.mean(data)

In [21]:
print(m)

6.14875


In [22]:
mdata = np.max(data)


In [23]:
data.size

2400

In [24]:
athritis = data

In [25]:
athritis.size


2400

In [26]:
np.max(athritis)

20.0

In [27]:
np.min(athritis)

0.0

In [28]:
np.std(athritis)

4.613833197118566

In [31]:
patient_0 = athritis[0, :]
print('max inflammation patient 0:', patient_0.max())

max inflammation patient 0: 18.0


In [32]:
np.max(data,axis=1)

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

In [34]:
print(athritis.max(axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [35]:
print(athritis.max(axis=0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]


In [38]:
print(athritis.max(axis=1).shape)
    

(60,)


In [42]:
std= np.std(athritis, axis=1)
avstd = np.mean(std)

print(avstd)



4.579294680644961


print(np.mean(np.std(athritis, axis=1))

In [43]:
print(np.mean(np.std(athritis, axis=1)))

4.579294680644961
